FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

# Set the working directory in the container
WORKDIR /usr/app

# Install necessary packages
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    git \
    cmake \
    build-essential \
    ca-certificates \
    libssl-dev 

RUN mkdir -p libs/SealLib SEAL src libs/KafkaLib/include libs/KafkaLib/lib certs SingleHeaders/base64 SingleHeaders/nlohmann

# Clone and build Microsoft SEAL with specified installation prefix
RUN git clone https://github.com/microsoft/SEAL.git ./SEAL && \
    cmake -S SEAL/. -B build -DCMAKE_INSTALL_PREFIX=./libs/SealLib && \
    cmake --build build && \
    cmake --install build && \
    rm -rf SEAL build

# Clone and build librdkafka with specified installation prefix
RUN git clone https://github.com/confluentinc/librdkafka.git ./librdkafka

RUN cd librdkafka && \
    ./configure --install-deps && \
    make && \
    make install && \
    cp -r win32 ./../libs/libs && \
    cp /usr/local/lib/librd* ../libs/KafkaLib/lib/. && \
    cp /usr/local/include/librdkafka/* ../libs/KafkaLib/include/. && \
    cd .. && \
    rm -rf librdkafka

RUN apt-get install -y wget && \
    wget -O SingleHeaders/nlohmann/json.hpp https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp && \
    wget -O SingleHeaders/nlohmann/json_fwd.hpp https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json_fwd.hpp && \
    wget -O SingleHeaders/base64/base64.hpp https://raw.githubusercontent.com/tobiaslocker/base64/master/include/base64.hpp

ENV LD_LIBRARY_PATH=/usr/app/libs/KafkaLib/lib:$LD_LIBRARY_PATH

# Copy src files to the working directory
COPY src/ ./src

RUN g++ -std=c++17 -O2 -Wall -Wextra -o microservice-c \
    src/properties/config.cpp src/main.cpp \
    src/SealService/SealService.cpp \
    src/events/consumer/consumer.cpp src/events/producer/producer.cpp \
    src/dataFormats/SealData/SealData.cpp src/dataFormats/ResultData/ResultData.cpp \
    -Isrc/SealService -Isrc/properties -Isrc/events/consumer -Isrc/events/producer \
    -Isrc/dataFormats/SealData -Isrc/dataFormats/ResultData \
    -ISingleHeaders/nlohmann \
    -ISingleHeaders/base64 \
    -Ilibs/KafkaLib/include \
    -Ilibs/SealLib/include/SEAL-4.1 \
    -Llibs/KafkaLib/lib \
    -Llibs/SealLib/lib -lrdkafka++ -lseal-4.1 -lssl -lcrypto -lm -Wl,-rpath,libs/KafkaLib/lib

CMD ["./microservice-c", "kubernetes"]