apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-b.fullname" . }}
  labels:
    {{- include "microservice-b.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
  selector:
    {{- include "microservice-b.selectorLabels" . | nindent 4 }}
